version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install Git
          command: |
            sudo apt-get update
            sudo apt-get install -y git
      - run:
          name: Configure Git
          command: |
            git config --global user.email "you@example.com"
            git config --global user.name "Your Name"
      - run:
          name: Clone Repos, Concatenate Rust Files, and Push using PAT
          command: |
            # Clone each repository
            git clone https://github.com/wndsrfr21/merge_add.git
            git clone https://github.com/wndsrfr21/merge_divide.git
            git clone https://github.com/wndsrfr21/merge_main.git
            
            # Create the merged.rs file
            touch merged.rs
            
            # Concatenate Rust source files from each cloned repo into merged.rs
            for repo in merge_add merge_divide merge_main; do
              for file in $(find $repo -type f -name '*.rs'); do
                cat "$file" >> merged.rs
                echo "" >> merged.rs # Ensure a newline between files
              done
            done
            
            # Prepare the new repository
            git init
            git remote add origin https://x-access-token:${GH_TOKEN}@github.com/wndsrfr21/merge_test.git
            git checkout -b main
            
            # Commit and push merged.rs to the repository
            git add merged.rs
            git commit -m "Concatenated Rust files from multiple repos into merged.rs"
            git push --set-upstream origin main

workflows:
  version: 2
  build_and_push:
    jobs:
      - build
