version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install Git
          command: |
            sudo apt-get update
            sudo apt-get install -y git
      - run:
          name: Configure Git
          command: |
            git config --global user.email "wndsrfr21@gmail.com"
            git config --global user.name "Alex"
      - run:
          name: Clone Repos
          command: |
            # Clone each repository ch
            git clone https://github.com/wndsrfr21/merge_add.git
            git clone https://github.com/wndsrfr21/merge_divide.git
            git clone https://github.com/wndsrfr21/merge_main.git
            
            # Create the merged.rs file
            touch merged.rs
            
      - run:
          name: Concatenate Specific Rust Files
          command: |
            # Assuming each repository has a known Rust file at its root
            cat ./merge_add/main.rs ./merge_divide/divide.rs ./merge_main/add.rs > merged.rs
            
      - run:
          name: Print merged.rs
          command: |
            cat merged.rs
      - run:
          name: Update merged_output Repo
          command: |
            # Clone the merge_test repository using the PAT for authentication
            git clone https://x-access-token:${GH_TOKEN}@github.com/wndsrfr21/merged_output.git
            
            # Navigate into the repository directory
            cd merged_output
            
            # Check and switch to the appropriate branch (main or master)
            if git rev-parse --verify main >/dev/null 2>&1; then
              git checkout main
            elif git rev-parse --verify master >/dev/null 2>&1; then
              git checkout master
            else
              echo "Error: Default branch (main or master) not found."
              exit 1
            fi
            
            # Copy the merged.rs file into the repository
            cp ../merged.rs .
            
            # Add, commit, and push the changes
            git add merged.rs
            git commit -m "Update merged.rs with latest changes"
            git push origin HEAD

workflows:
  version: 2
  build_and_push:
    jobs:
      - build
