version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install Git
          command: |
            sudo apt-get update
            sudo apt-get install -y git
      - run:
          name: Configure Git
          command: |
            git config --global user.email "you@example.com"
            git config --global user.name "Your Name"
      - run:
          name: Clone Repos and Concatenate Rust Files
          command: |
            # Clone each source repository
            git clone https://github.com/wndsrfr21/merge_add.git
            git clone https://github.com/wndsrfr21/merge_divide.git
            git clone https://github.com/wndsrfr21/merge_main.git
            
            # Create the merged.rs file
            touch merged.rs
            
            # Concatenate Rust source files from each cloned repo into merged.rs
            for repo in merge_add merge_divide merge_main; do
              for file in $(find $repo -type f -name '*.rs'); do
                cat "$file" >> merged.rs
                echo "" >> merged.rs # Add a newline between files
              done
            done
      - run:
          name: Push merged.rs to merged_output Repo on app Branch
          command: |
            # Clone the target repository using the PAT for authentication
            git clone https://x-access-token:${GH_TOKEN}@github.com/wndsrfr21/merged_output.git
            
            # Navigate into the repository directory
            cd merged_output
            
            # Check if the 'app' branch exists and switch to it; create it if it doesn't exist
            if git show-ref --verify --quiet refs/heads/app; then
              git checkout app
            else
              git checkout -b app
            fi
            
            # Copy merged.rs to the repository
            cp ../merged.rs .
            
            # Add, commit, and push the changes to the 'app' branch
            git add merged.rs
            git commit -m "Update merged.rs with the latest changes [skip ci]"
            git push origin HEAD

workflows:
  version: 2
  build_and_push:
    jobs:
      - build
