version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install Git
          command: |
            sudo apt-get update
            sudo apt-get install -y git
      - run:
          name: Configure Git
          command: |
            git config --global user.email "wndsrfr21@gmail.com"
            git config --global user.name "Alex"
      - run:
          name: Clone Repos, Concatenate Rust Files, and Push
          command: |
            # Clone each repository
            git clone https://github.com/wndsrfr21/merge_add.git
            git clone https://github.com/wndsrfr21/merge_divide.git
            git clone https://github.com/wndsrfr21/merge_main.git
            
            # Create a directory for the final repository and initialize it
            mkdir final_repo && cd final_repo
            git init
            
            # Concatenate Rust source files from each cloned repo into a single file
            # Adjust the file pattern (*.rs) as needed for your specific case
            for repo in ../merge_add ../merge_divide ../merge_main; do
              for file in $repo/*.rs; do
                cat $file >> merged.rs
                echo "" >> merged.rs # Ensure a newline between files
              done
            done

            # print out merged.rs to confirm successful merge
            cat merged.rs
            
            # Add, commit, and push the combined file to the new repository
            git add merged.rs
            git commit -m "Concatenated Rust files from multiple repos"
            git remote add origin https://github.com/wndsrfr21/merge_test.git
            git branch -M main
            git push -u origin main

workflows:
  version: 2
  build_and_push:
    jobs:
      - build
